version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - cd backend
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
      - ls
      - mv target/*.jar app.jar
      - ls
artifacts:
  files:
    - backend/app.jar